### ISSUE TITLE
Startpage logo positioning bug, mobile landscape

### ISSUE THREAD

**Issue by jberglinds** [studieresan/studs-web#26]
On mobile devices, in landscape mode, the logo in the intro disappears under the navbar when fully scrolled up. 
See attached screenshot. 

<img width="715" alt="skarmavbild 2017-12-13 kl 16 22 00" src="https://user-images.githubusercontent.com/6368728/33946327-c7fa46ca-e021-11e7-8291-d33b7272c31b.png">

Note that this happens on all mobile devices, not iPhone X specifically.

**Comment by aronstrandberg** [comment]
Duplicate of #24, but this one had more info I'll close that one

**Comment by jberglinds** [comment]
"more info" haha

**Comment by jeppes** [comment]
@jberglinds can this be closed?

**Comment by jberglinds** [comment]
No, the issue is still present. Can be reproduced in the responsive design mode of any browser
