### ISSUE TITLE
Controlled inputs have both value and placeholder

### ISSUE THREAD

**Issue by aronstrandberg** [studieresan/studs-web#38]
The placeholders don't disappear when the input value is fetched in the User edit page (maybe other pages as well)

**Example**:
<img width="316" alt="screenshot-2017-12-17_14-49-05" src="https://user-images.githubusercontent.com/2405802/34080127-7cf49b2e-e339-11e7-98e8-3db54665db90.png">

**Comment by aronstrandberg** [comment]
Update: it only happens in Safari

**Comment by jeppes** [comment]
@aronstrandberg safari doesn't work at all for me :(, maybe this is should be a part of the DX hack?

**Comment by jeppes** [comment]
@aronstrandberg this seems to be fixed on the latest master. Should we close it?

**Comment by aronstrandberg** [comment]
The issue is still there for me :(
